name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '30 14 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: guilyx/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka-simple"
          COMMIT_MESSAGE: "Updated simple waka stats section"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
    
